// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status assetu przechowywany w tabeli `assets`.
 */
export type AssetStatus = "UPLOADING" | "QUARANTINED" | "SCANNING" | "REJECTED" | "INFECTED" | "SCAN_FAILED" | "CLEAN_DRAFT" | "PUBLISHED" | "ARCHIVED";
