// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetSummary } from "./AssetSummary";

/**
 * Odpowiedź `GET /assets`.
 */
export type AssetListResponse = { items: Array<AssetSummary>, 
/**
 * Kursor następnej strony (`?cursor=`), `null` na ostatniej stronie.
 */
nextCursor: string | null, };
