// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetStatus } from "./AssetStatus";

/**
 * Odpowiedź operacji zmieniających status (`publish`, `rescan`).
 */
export type AssetStatusResponse = { assetId: string, status: AssetStatus, };
