// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widok listy assetów (`GET /assets?view=...`).
 */
export type AssetView = "gallery" | "mine" | "drafts";
