// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetCategory } from "./AssetCategory";

/**
 * Metadane assetu: ciało `PUT /assets/{assetId}/metadata` i odpowiedź.
 * Żądanie zastępuje całość: brak pola albo `null` usuwa wartość.
 */
export type AssetMetadata = { title: string | null, category: AssetCategory | null, seasonId: string | null, competitionId: string | null, matchId: string | null, playerIds: Array<string>, tags: Array<string>, };
