// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetStatus } from "./AssetStatus";

/**
 * Asset na liście.
 */
export type AssetSummary = { assetId: string, status: AssetStatus, title: string | null, originalFilename: string, contentType: string, sizeBytes: number, 
/**
 * Milisekundy od epoki.
 */
createdAt: number, updatedAt: number, 
/**
 * Krótko żyjący URL do podglądu (tylko obrazy): miniatura dla A i B,
 * podgląd ze znakiem wodnym dla D, `null` w „moich zgłoszeniach”.
 */
previewUrl: string | null, };
