// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kategoria assetu (rozdział 7.4).
 */
export type AssetCategory = "MATCH_PHOTO" | "TRAINING_PHOTO" | "VIDEO" | "BRAND_IDENTITY" | "SPONSOR_MATERIAL" | "PRESS_DOCUMENT";
