// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rodzaj słownika. W ścieżce API liczba mnoga (`/dictionaries/players/…`),
 * w DynamoDB stała nazwa partycji (`PLAYER`).
 */
export type DictionaryKind = "players" | "seasons" | "competitions" | "matches" | "sponsors";
