// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Competition } from "./Competition";
import type { Match } from "./Match";
import type { Player } from "./Player";
import type { Season } from "./Season";
import type { Sponsor } from "./Sponsor";

/**
 * Odpowiedź `GET /dictionaries`: wszystkie słowniki naraz (są małe), każda
 * lista posortowana do wyświetlenia. Sponsorów widzi tylko A.
 */
export type Dictionaries = { players: Array<Player>, seasons: Array<Season>, competitions: Array<Competition>, matches: Array<Match>, sponsors: Array<Sponsor>, };
