// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Odpowiedź `GET /assets/{assetId}/download`.
 */
export type DownloadResponse = { url: string, expiresInSeconds: number, };
