// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

export type Player = { id: string, name: string, 
/**
 * Numer na koszulce (1–99).
 */
number: number | null, position: Position | null, 
/**
 * Zawodnik w obecnej kadrze (byli zawodnicy zostają w słowniku, bo
 * odwołują się do nich archiwalne zdjęcia).
 */
active: boolean, };
