// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pozycja zawodnika.
 */
export type Position = "GOALKEEPER" | "DEFENDER" | "MIDFIELDER" | "FORWARD";
