// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetStatus } from "./AssetStatus";

/**
 * Odpowiedź `POST /assets/{assetId}/publish`.
 */
export type PublishResponse = { assetId: string, status: AssetStatus, };
