// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sezon, np. `id = "2025-26"`, `name = "2025/26"`.
 */
export type Season = { id: string, name: string, };
